update workflow

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -9,34 +9,23 @@ env:
   REPO: gns3-server  
 
 jobs:
-  dependencies_init:
-    runs-on: ubuntu-latest
-    outputs:
-      version: ${{ steps.version.outputs.version }}
-    steps:
-    - name: submodule init
-      uses: actions/checkout@v4
-      with:
-        submodules: true
-        fetch-depth: 0
-
-    - name: set VERSION
-      id: version
-      run: |
-        VERSION=$(sed -nE 's/^gns3-server==(.+)$/\1/p' requirements.txt)
-        if [ -z "$VERSION" ]; then
-          echo "VERSION not found in requirements.txt" >&2
-          exit 1
-        fi
-        echo "version=$VERSION" >> "$GITHUB_OUTPUT"
-
   build_and_deploy:
     runs-on: ubuntu-latest
-    needs: dependencies_init
     steps:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
+          submodules: true
+
+      - name: set VERSION
+        id: version
+        run: |
+          VERSION=$(sed -nE 's/^gns3-server==(.+)$/\1/p' requirements.txt)
+          if [ -z "$VERSION" ]; then
+            echo "VERSION not found in requirements.txt" >&2
+            exit 1
+          fi
+          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
 
       - name: set up Docker Buildx
         uses: docker/setup-buildx-action@3.10.0
